name: Deploy Website
   on:
     push:
       branches: [ main ]
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Deploy via SSH
           uses: appleboy/ssh-action@v0.1.7
           with:
             host: ${{ secrets.HOST_IP }}
             port: ${{ secrets.SSH_PORT }}
             username: deploy
             key: ${{ secrets.DEPLOY_KEY }}
             script: |
               cd /var/www/ila.jefahnierocks.com
               git pull
