name: Deploy Ila's Ocean Wonderland

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: verlyn13/kids-deploy-actions/.github/workflows/deploy.yml@main
    with:
      build_command: 'npm install && npm run build'
      build_output_dir: 'dist'
      remote_target_dir: '/var/www/kidsites/ila'
    secrets: inherit
    permissions:
      actions: read
      contents: read
